[workspace]

members = [
    "tenkei90/problem1",
    "atcoder100/problem1",
    "atcoder100/problem2",
    "atcoder100/problem3",
    "atcoder100/problem4",
    "atcoder100/problem5",
    "atcoder100/problem6",
    "atcoder100/problem7",
    "atcoder100/problem8",
    "atcoder100/problem9",
    "atcoder100/problem10",
]
